version: 2.1


jobs:

  test:

    docker:
      - image: cimg/python:3.12


    steps:

      # Download GitHub code
      - checkout


      # Restore pip cache
      - restore_cache:
          keys:
            - python-cache-{{ checksum "requirements.txt" }}
            - python-cache


      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt


      # Save cache
      - save_cache:
          key: python-cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip


      # Run tests
      - run:
          name: Run Tests
          command: |
            pytest



  build:

    docker:
      - image: cimg/python:3.12


    steps:

      - checkout


      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt


      - run:
          name: Check Python Application
          command: |
            python -m py_compile app.py



workflows:

  weather-app-ci:

    jobs:

      - test

      - build:
          requires:
            - test
